apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: sidecar-poc-cache.redis.cache.windows.net:6380
  - name: useEntraID
    value: "true"
  - name: enableTLS
    value: "true"